# قم بتبديل ملف هذا من copy لي pord ونسخة اخرى منه dev
# docker-compose.yml هو ملف يحتوي على اعدادات ال docker 
# هو مرتبط بملف ال docker
# قبل القيام باي كتابة كود يجب ان يكون في الطرفية اما down or up
#docker-compose -f docker-compose-dev/prod.yml up -d  
# pytest تصفحه
version: '3'
services:
  api:
    # build: . 1
    image: docer123docer/fastapi
    depends_on:
      - postgres
    ports:
      - "80:8000" # <port on localhost>:<port on container> وهو يتغير ايضا في بوست مان
    # volumes:
      # - ./:/usr/src/app:ro
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      # - DATABASE_HOSTNAME=localhost
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME} #postgres
      - DATABASE_PORT=${DATABASE_PORT} #5432
      - DATABASE_PASSWORD=${DATABASE_PASSWORD} #Admin
      - DATABASE_NAME=${DATABASE_NAME} #fastapi
      - DATABASE_USERNAME=${DATABASE_USERNAME} #postgres
      - SECRET_KEY=${SECRET_KEY}  #09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=${ALGORITHM} #HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES} #30
  postgres:
    image: postgres
    environment:
      # POSTGRES_USER: postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD} #Admin
      - POSTGRES_DB=${DATABASE_NAME} #fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    